#!/bin/bash

if [ ${#@} -eq 0 ]
then
  echo Error: At least one database name is required as an input
  exit
fi

for i in ${@}; do
  echo Cleanup and backup up database: $i
  ls -t *_$i.sql | sed -e '1,7d' | xargs -I {} rm {}
  pg_dump $i > `date +\%Y-\%m-\%d_\%H\%M`_$i.sql
done
